import { 
  User, Category, Brand, Warehouse, Product, Batch, StockTransfer, 
  Order, Invoice, DeliveryTask, Coupon, AuditLog, SalesmanLead, SystemMetrics 
} from '../../types';

export class MedSupplyStore {
  public users: User[] = [
    {
      id: 'usr-001',
      name: 'Dr. Arthur Vance',
      email: 'superadmin@medsupply.com',
      role: 'SUPER_ADMIN',
      phone: '+1 (800) 555-0100',
      status: 'ACTIVE',
      createdAt: '2025-01-10T08:00:00Z',
    },
    {
      id: 'usr-002',
      name: 'Sarah Jenkins',
      email: 'admin@medsupply.com',
      role: 'ADMIN',
      phone: '+1 (800) 555-0101',
      status: 'ACTIVE',
      createdAt: '2025-01-15T09:30:00Z',
    },
    {
      id: 'usr-003',
      name: 'Carlos Mendez',
      email: 'warehouse@medsupply.com',
      role: 'WAREHOUSE_STAFF',
      phone: '+1 (800) 555-0102',
      status: 'ACTIVE',
      createdAt: '2025-02-01T10:15:00Z',
    },
    {
      id: 'usr-004',
      name: 'Marcus Brody',
      email: 'sales@medsupply.com',
      role: 'SALESMAN',
      phone: '+1 (800) 555-0103',
      status: 'ACTIVE',
      createdAt: '2025-02-10T11:00:00Z',
    },
    {
      id: 'usr-005',
      name: 'David Miller',
      email: 'delivery@medsupply.com',
      role: 'DELIVERY_BOY',
      phone: '+1 (800) 555-0104',
      status: 'ACTIVE',
      createdAt: '2025-03-01T07:45:00Z',
    },
    {
      id: 'usr-006',
      name: 'Apollo Hospital System',
      email: 'b2b@apollo.org',
      role: 'B2B_CUSTOMER',
      phone: '+1 (800) 555-0199',
      licenseNumber: 'DL-MH-994821-EXP2028',
      gstin: '27AAAAA0000A1Z5',
      creditLimit: 150000,
      usedCredit: 42500,
      creditTerms: 'NET_30',
      address: '742 Evergreen Medical Parkway, Suite 400',
      city: 'Chicago',
      state: 'IL',
      pincode: '60601',
      status: 'ACTIVE',
      createdAt: '2025-01-05T14:20:00Z',
    },
    {
      id: 'usr-007',
      name: 'City Care Pharmacy',
      email: 'b2b@citycare.com',
      role: 'B2B_CUSTOMER',
      phone: '+1 (800) 555-0188',
      licenseNumber: 'DL-IL-882143-EXP2027',
      gstin: '17BBBBB1111B2Z8',
      creditLimit: 50000,
      usedCredit: 12800,
      creditTerms: 'NET_15',
      address: '108 West Michigan Ave',
      city: 'Chicago',
      state: 'IL',
      pincode: '60605',
      status: 'ACTIVE',
      createdAt: '2025-02-18T16:00:00Z',
    },
    {
      id: 'usr-008',
      name: 'Dr. Emily Harrison (Patient)',
      email: 'patient@gmail.com',
      role: 'B2C_CUSTOMER',
      phone: '+1 (800) 555-0177',
      address: '42 Pine St, Apt 3B',
      city: 'Chicago',
      state: 'IL',
      pincode: '60611',
      status: 'ACTIVE',
      createdAt: '2025-04-12T12:00:00Z',
    }
  ];

  public categories: Category[] = [
    {
      id: 'cat-01',
      name: 'Antibiotics & Antimicrobials',
      code: 'ANTIBIO',
      description: 'Prescription oral and injectable antibiotics',
      icon: 'Pill',
      isPrescriptionRequired: true,
    },
    {
      id: 'cat-02',
      name: 'Cold-Chain Biologicals & Vaccines',
      code: 'COLDCHAIN',
      description: 'Temperature sensitive vaccines, insulins, and biological agents',
      icon: 'ThermometerSnowflake',
      isPrescriptionRequired: true,
    },
    {
      id: 'cat-03',
      name: 'Surgical & ICU Consumables',
      code: 'SURGICAL',
      description: 'Gloves, syringes, IV sets, catheters, and sterile drapes',
      icon: 'Syringe',
      isPrescriptionRequired: false,
    },
    {
      id: 'cat-04',
      name: 'Diagnostic & Electrodes',
      code: 'DIAGNOSTIC',
      description: 'ECG sensors, glucometer strips, diagnostic reagents',
      icon: 'Activity',
      isPrescriptionRequired: false,
    },
    {
      id: 'cat-05',
      name: 'Emergency Respiratory & Oxygen',
      code: 'RESPIRATORY',
      description: 'Medical oxygen cylinders, nebulizers, ventilators masks',
      icon: 'Wind',
      isPrescriptionRequired: true,
    },
  ];

  public brands: Brand[] = [
    { id: 'br-01', name: 'Pfizer MedTech', country: 'USA', contactEmail: 'supply@pfizer.com', isGmpCertified: true },
    { id: 'br-02', name: 'Roche Diagnostics', country: 'Switzerland', contactEmail: 'b2b@roche.com', isGmpCertified: true },
    { id: 'br-03', name: 'BD (Becton Dickinson)', country: 'USA', contactEmail: 'orders@bd.com', isGmpCertified: true },
    { id: 'br-04', name: 'Sun Pharma B2B', country: 'India', contactEmail: 'institutional@sunpharma.com', isGmpCertified: true },
    { id: 'br-05', name: 'Medtronic Surgical', country: 'USA', contactEmail: 'logistics@medtronic.com', isGmpCertified: true },
  ];

  public warehouses: Warehouse[] = [
    {
      id: 'wh-01',
      name: 'Central Enterprise Logistics Hub',
      code: 'WH-CHI-CENTRAL',
      type: 'CENTRAL_HUB',
      address: '1200 Logistics Boulevard, Bay 4',
      city: 'Chicago',
      capacitySqFt: 120000,
      tempControl: 'ROOM_TEMP',
      managerName: 'Carlos Mendez',
      status: 'OPERATIONAL',
    },
    {
      id: 'wh-02',
      name: 'North Cold-Chain Vault (2-8°C)',
      code: 'WH-MPLS-COLD',
      type: 'REGIONAL_COLD_CHAIN',
      address: '450 Pharma Park Drive',
      city: 'Minneapolis',
      capacitySqFt: 45000,
      tempControl: 'COLD_CHAIN_2_8C',
      managerName: 'Elena Rostova',
      status: 'OPERATIONAL',
    },
    {
      id: 'wh-03',
      name: 'Metro Transit Emergency Depot',
      code: 'WH-DAL-TRANSIT',
      type: 'TRANSIT_FULFILLMENT',
      address: '89 Express Freight Road',
      city: 'Dallas',
      capacitySqFt: 30000,
      tempControl: 'ROOM_TEMP',
      managerName: 'Marcus Brody',
      status: 'OPERATIONAL',
    },
    {
      id: 'wh-04',
      name: 'Apollo Hospital Onsite Depot',
      code: 'WH-APOLLO-ONSITE',
      type: 'HOSPITAL_ONSITE',
      address: '742 Evergreen Medical Pkwy, Bldg B',
      city: 'Chicago',
      capacitySqFt: 15000,
      tempControl: 'ROOM_TEMP',
      managerName: 'Dr. Arthur Vance',
      status: 'OPERATIONAL',
    }
  ];

  public products: Product[] = [
    {
      id: 'prod-01',
      name: 'Amoxicillin Trihydrate 500mg Capsules',
      sku: 'AMX-500-CAP',
      hsnCode: '30041010',
      categoryId: 'cat-01',
      categoryName: 'Antibiotics & Antimicrobials',
      brandId: 'br-04',
      brandName: 'Sun Pharma B2B',
      description: 'Broad-spectrum beta-lactam antibiotic. Box of 100 capsules (10x10 strips).',
      unitOfMeasure: 'BOX',
      b2cPrice: 28.50,
      b2bPriceTier1: 22.00,
      b2bPriceTier2: 18.50,
      mrp: 35.00,
      taxRatePercent: 12,
      prescriptionRequired: true,
      minStockAlert: 100,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
      storageCondition: 'ROOM_TEMP',
      active: true,
    },
    {
      id: 'prod-02',
      name: 'Ceftriaxone Sodium 1g Injectable Vials',
      sku: 'CFT-1G-VIAL',
      hsnCode: '30042010',
      categoryId: 'cat-01',
      categoryName: 'Antibiotics & Antimicrobials',
      brandId: 'br-01',
      brandName: 'Pfizer MedTech',
      description: 'Third-generation cephalosporin IV/IM injection. Pack of 25 sterile vials.',
      unitOfMeasure: 'PACK',
      b2cPrice: 145.00,
      b2bPriceTier1: 115.00,
      b2bPriceTier2: 98.00,
      mrp: 175.00,
      taxRatePercent: 12,
      prescriptionRequired: true,
      minStockAlert: 50,
      imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=500&auto=format&fit=crop&q=80',
      storageCondition: 'ROOM_TEMP',
      active: true,
    },
    {
      id: 'prod-03',
      name: 'Insulin Glargine 100 IU/ml Cold Pens',
      sku: 'INS-GLR-100',
      hsnCode: '30043110',
      categoryId: 'cat-02',
      categoryName: 'Cold-Chain Biologicals & Vaccines',
      brandId: 'br-01',
      brandName: 'Pfizer MedTech',
      description: 'Long-acting basal analog insulin. Pack of 5 pre-filled 3ml SoloStar pens. Strictly Cold-Chain 2-8°C.',
      unitOfMeasure: 'PACK',
      b2cPrice: 110.00,
      b2bPriceTier1: 89.00,
      b2bPriceTier2: 76.00,
      mrp: 130.00,
      taxRatePercent: 5,
      prescriptionRequired: true,
      minStockAlert: 40,
      imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80',
      storageCondition: 'COLD_CHAIN_2_8C',
      active: true,
    },
    {
      id: 'prod-04',
      name: 'BD Luer-Lok Syringes 5ml w/ 21G Needles',
      sku: 'SYR-BD-5ML',
      hsnCode: '90183100',
      categoryId: 'cat-03',
      categoryName: 'Surgical & ICU Consumables',
      brandId: 'br-03',
      brandName: 'BD (Becton Dickinson)',
      description: 'Sterile single-use syringe with safety needle shield. Box of 100 individually wrapped units.',
      unitOfMeasure: 'BOX',
      b2cPrice: 24.00,
      b2bPriceTier1: 16.50,
      b2bPriceTier2: 13.00,
      mrp: 29.00,
      taxRatePercent: 18,
      prescriptionRequired: false,
      minStockAlert: 200,
      imageUrl: 'https://images.unsplash.com/photo-1628595351029-c2bf17511435?w=500&auto=format&fit=crop&q=80',
      storageCondition: 'ROOM_TEMP',
      active: true,
    },
    {
      id: 'prod-05',
      name: 'Surgical Nitrile Gloves Powder-Free L',
      sku: 'GLV-NIT-L',
      hsnCode: '40151100',
      categoryId: 'cat-03',
      categoryName: 'Surgical & ICU Consumables',
      brandId: 'br-03',
      brandName: 'BD (Becton Dickinson)',
      description: 'Medical grade exam gloves, textured fingertips. Box of 100 ambidextrous gloves.',
      unitOfMeasure: 'BOX',
      b2cPrice: 18.00,
      b2bPriceTier1: 12.00,
      b2bPriceTier2: 9.50,
      mrp: 22.00,
      taxRatePercent: 18,
      prescriptionRequired: false,
      minStockAlert: 300,
      imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80',
      storageCondition: 'ROOM_TEMP',
      active: true,
    },
    {
      id: 'prod-06',
      name: 'Medtronic Silver ECG Electrodes (Pack 100)',
      sku: 'ECG-SLV-100',
      hsnCode: '90181100',
      categoryId: 'cat-04',
      categoryName: 'Diagnostic & Electrodes',
      brandId: 'br-05',
      brandName: 'Medtronic Surgical',
      description: 'High conductivity hydrogel ECG diagnostic electrodes for ICU monitoring.',
      unitOfMeasure: 'PACK',
      b2cPrice: 32.00,
      b2bPriceTier1: 22.00,
      b2bPriceTier2: 17.50,
      mrp: 40.00,
      taxRatePercent: 18,
      prescriptionRequired: false,
      minStockAlert: 80,
      imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=500&auto=format&fit=crop&q=80',
      storageCondition: 'ROOM_TEMP',
      active: true,
    },
    {
      id: 'prod-07',
      name: 'Medical Oxygen Cylinder D-Type 1360L',
      sku: 'OXY-CYL-D13',
      hsnCode: '28044010',
      categoryId: 'cat-05',
      categoryName: 'Emergency Respiratory & Oxygen',
      brandId: 'br-05',
      brandName: 'Medtronic Surgical',
      description: 'High pressure seamless steel cylinder filled with 99.5% pure medical grade oxygen.',
      unitOfMeasure: 'CYLINDER',
      b2cPrice: 220.00,
      b2bPriceTier1: 175.00,
      b2bPriceTier2: 145.00,
      mrp: 260.00,
      taxRatePercent: 12,
      prescriptionRequired: true,
      minStockAlert: 20,
      imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500&auto=format&fit=crop&q=80',
      storageCondition: 'ROOM_TEMP',
      active: true,
    },
    {
      id: 'prod-08',
      name: 'COVID-19 / Flu Multi-Strain Vaccine',
      sku: 'VAC-FLU-2026',
      hsnCode: '30022010',
      categoryId: 'cat-02',
      categoryName: 'Cold-Chain Biologicals & Vaccines',
      brandId: 'br-02',
      brandName: 'Roche Diagnostics',
      description: 'Quadrivalent influenza + updated strain mRNA vaccine. Box of 10 single dose prefilled syringes.',
      unitOfMeasure: 'BOX',
      b2cPrice: 310.00,
      b2bPriceTier1: 250.00,
      b2bPriceTier2: 210.00,
      mrp: 360.00,
      taxRatePercent: 5,
      prescriptionRequired: true,
      minStockAlert: 30,
      imageUrl: 'https://images.unsplash.com/photo-1618961734760-466979ce35b0?w=500&auto=format&fit=crop&q=80',
      storageCondition: 'COLD_CHAIN_2_8C',
      active: true,
    }
  ];

  public batches: Batch[] = [
    // Amoxicillin Batches (One Near Expiry FEFO test)
    {
      id: 'btc-101',
      productId: 'prod-01',
      productName: 'Amoxicillin Trihydrate 500mg Capsules',
      productSku: 'AMX-500-CAP',
      warehouseId: 'wh-01',
      warehouseName: 'Central Enterprise Logistics Hub',
      batchNumber: 'AMX-2025-081',
      manufacturingDate: '2024-08-10',
      expiryDate: '2026-08-15', // Near expiry (<30 days!)
      mrp: 35.00,
      b2bPrice: 18.50,
      quantityOnHand: 180,
      quantityReserved: 20,
      quantityAvailable: 160,
      coldChainMonitored: false,
      status: 'NEAR_EXPIRY',
    },
    {
      id: 'btc-102',
      productId: 'prod-01',
      productName: 'Amoxicillin Trihydrate 500mg Capsules',
      productSku: 'AMX-500-CAP',
      warehouseId: 'wh-01',
      warehouseName: 'Central Enterprise Logistics Hub',
      batchNumber: 'AMX-2026-012',
      manufacturingDate: '2025-02-01',
      expiryDate: '2027-03-30',
      mrp: 35.00,
      b2bPrice: 18.50,
      quantityOnHand: 850,
      quantityReserved: 50,
      quantityAvailable: 800,
      coldChainMonitored: false,
      status: 'ACTIVE',
    },
    // Insulin Batches (Cold chain monitored)
    {
      id: 'btc-103',
      productId: 'prod-03',
      productName: 'Insulin Glargine 100 IU/ml Cold Pens',
      productSku: 'INS-GLR-100',
      warehouseId: 'wh-02',
      warehouseName: 'North Cold-Chain Vault (2-8°C)',
      batchNumber: 'INS-2026-004',
      manufacturingDate: '2025-01-15',
      expiryDate: '2026-09-10',
      mrp: 130.00,
      b2bPrice: 76.00,
      quantityOnHand: 320,
      quantityReserved: 30,
      quantityAvailable: 290,
      coldChainMonitored: true,
      tempReadingCelsius: 3.8,
      status: 'ACTIVE',
    },
    // Ceftriaxone Vials (Near Expiry)
    {
      id: 'btc-104',
      productId: 'prod-02',
      productName: 'Ceftriaxone Sodium 1g Injectable Vials',
      productSku: 'CFT-1G-VIAL',
      warehouseId: 'wh-01',
      warehouseName: 'Central Enterprise Logistics Hub',
      batchNumber: 'CFT-2025-992',
      manufacturingDate: '2024-09-01',
      expiryDate: '2026-08-05', // Near Expiry!
      mrp: 175.00,
      b2bPrice: 98.00,
      quantityOnHand: 95,
      quantityReserved: 15,
      quantityAvailable: 80,
      coldChainMonitored: false,
      status: 'NEAR_EXPIRY',
    },
    // Syringes
    {
      id: 'btc-105',
      productId: 'prod-04',
      productName: 'BD Luer-Lok Syringes 5ml w/ 21G Needles',
      productSku: 'SYR-BD-5ML',
      warehouseId: 'wh-01',
      warehouseName: 'Central Enterprise Logistics Hub',
      batchNumber: 'SYR-2026-440',
      manufacturingDate: '2025-01-10',
      expiryDate: '2028-12-31',
      mrp: 29.00,
      b2bPrice: 13.00,
      quantityOnHand: 2400,
      quantityReserved: 100,
      quantityAvailable: 2300,
      coldChainMonitored: false,
      status: 'ACTIVE',
    },
    // Gloves
    {
      id: 'btc-106',
      productId: 'prod-05',
      productName: 'Surgical Nitrile Gloves Powder-Free L',
      productSku: 'GLV-NIT-L',
      warehouseId: 'wh-01',
      warehouseName: 'Central Enterprise Logistics Hub',
      batchNumber: 'GLV-2026-881',
      manufacturingDate: '2025-02-14',
      expiryDate: '2027-06-30',
      mrp: 22.00,
      b2bPrice: 9.50,
      quantityOnHand: 1800,
      quantityReserved: 200,
      quantityAvailable: 1600,
      coldChainMonitored: false,
      status: 'ACTIVE',
    },
    // ECG Electrodes
    {
      id: 'btc-107',
      productId: 'prod-06',
      productName: 'Medtronic Silver ECG Electrodes (Pack 100)',
      productSku: 'ECG-SLV-100',
      warehouseId: 'wh-03',
      warehouseName: 'Metro Transit Emergency Depot',
      batchNumber: 'ECG-2026-102',
      manufacturingDate: '2025-03-01',
      expiryDate: '2027-11-20',
      mrp: 40.00,
      b2bPrice: 17.50,
      quantityOnHand: 450,
      quantityReserved: 0,
      quantityAvailable: 450,
      coldChainMonitored: false,
      status: 'ACTIVE',
    },
    // Vaccine Batch
    {
      id: 'btc-108',
      productId: 'prod-08',
      productName: 'COVID-19 / Flu Multi-Strain Vaccine',
      productSku: 'VAC-FLU-2026',
      warehouseId: 'wh-02',
      warehouseName: 'North Cold-Chain Vault (2-8°C)',
      batchNumber: 'VAC-2026-779',
      manufacturingDate: '2025-03-10',
      expiryDate: '2026-11-15',
      mrp: 360.00,
      b2bPrice: 210.00,
      quantityOnHand: 210,
      quantityReserved: 10,
      quantityAvailable: 200,
      coldChainMonitored: true,
      tempReadingCelsius: 4.1,
      status: 'ACTIVE',
    }
  ];

  public stockTransfers: StockTransfer[] = [
    {
      id: 'trf-01',
      transferNumber: 'ST-2026-0091',
      fromWarehouseId: 'wh-01',
      fromWarehouseName: 'Central Enterprise Logistics Hub',
      toWarehouseId: 'wh-04',
      toWarehouseName: 'Apollo Hospital Onsite Depot',
      productId: 'prod-04',
      productName: 'BD Luer-Lok Syringes 5ml w/ 21G Needles',
      batchId: 'btc-105',
      batchNumber: 'SYR-2026-440',
      quantity: 500,
      requestedBy: 'Carlos Mendez',
      approvedBy: 'Sarah Jenkins',
      status: 'COMPLETED',
      createdAt: '2026-07-20T10:00:00Z',
      notes: 'Emergency replenishment for ICU surgical bay.',
    }
  ];

  public orders: Order[] = [
    {
      id: 'ord-1001',
      orderNumber: 'MSO-B2B-2026-0811',
      orderType: 'B2B',
      customerId: 'usr-006',
      customerName: 'Apollo Hospital System',
      customerEmail: 'b2b@apollo.org',
      salesmanId: 'usr-004',
      salesmanName: 'Marcus Brody',
      deliveryBoyId: 'usr-005',
      deliveryBoyName: 'David Miller',
      warehouseId: 'wh-01',
      warehouseName: 'Central Enterprise Logistics Hub',
      items: [
        {
          id: 'item-01',
          productId: 'prod-01',
          batchId: 'btc-101',
          productName: 'Amoxicillin Trihydrate 500mg Capsules',
          productSku: 'AMX-500-CAP',
          batchNumber: 'AMX-2025-081',
          quantity: 100,
          unitPrice: 18.50,
          mrp: 35.00,
          taxRate: 12,
          taxAmount: 222.00,
          totalPrice: 2072.00,
        },
        {
          id: 'item-02',
          productId: 'prod-04',
          batchId: 'btc-105',
          productName: 'BD Luer-Lok Syringes 5ml w/ 21G Needles',
          productSku: 'SYR-BD-5ML',
          batchNumber: 'SYR-2026-440',
          quantity: 200,
          unitPrice: 13.00,
          mrp: 29.00,
          taxRate: 18,
          taxAmount: 468.00,
          totalPrice: 3068.00,
        }
      ],
      subtotal: 4450.00,
      taxAmount: 690.00,
      discountAmount: 140.00,
      totalAmount: 5000.00,
      paymentStatus: 'CREDIT_APPROVED',
      paymentMethod: 'CREDIT_TERM',
      orderStatus: 'OUT_FOR_DELIVERY',
      deliveryAddress: '742 Evergreen Medical Parkway, Bay 2 Receiving Dock, Chicago IL 60601',
      poNumber: 'PO-APOLLO-2026-99',
      createdAt: '2026-07-22T14:30:00Z',
      updatedAt: '2026-07-23T05:00:00Z',
    },
    {
      id: 'ord-1002',
      orderNumber: 'MSO-B2C-2026-0942',
      orderType: 'B2C',
      customerId: 'usr-008',
      customerName: 'Dr. Emily Harrison (Patient)',
      customerEmail: 'patient@gmail.com',
      warehouseId: 'wh-02',
      warehouseName: 'North Cold-Chain Vault (2-8°C)',
      items: [
        {
          id: 'item-03',
          productId: 'prod-03',
          batchId: 'btc-103',
          productName: 'Insulin Glargine 100 IU/ml Cold Pens',
          productSku: 'INS-GLR-100',
          batchNumber: 'INS-2026-004',
          quantity: 1,
          unitPrice: 110.00,
          mrp: 130.00,
          taxRate: 5,
          taxAmount: 5.50,
          totalPrice: 115.50,
        }
      ],
      subtotal: 110.00,
      taxAmount: 5.50,
      discountAmount: 10.00,
      totalAmount: 105.50,
      paymentStatus: 'PAID',
      paymentMethod: 'RAZORPAY',
      orderStatus: 'DELIVERED',
      deliveryAddress: '42 Pine St, Apt 3B, Chicago IL 60611',
      prescriptionUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300',
      createdAt: '2026-07-21T09:15:00Z',
      updatedAt: '2026-07-21T11:45:00Z',
    }
  ];

  public invoices: Invoice[] = [
    {
      id: 'inv-8801',
      invoiceNumber: 'INV-MS-2026-0811',
      orderId: 'ord-1001',
      orderNumber: 'MSO-B2B-2026-0811',
      customerId: 'usr-006',
      customerName: 'Apollo Hospital System',
      gstin: '27AAAAA0000A1Z5',
      subtotal: 4450.00,
      cgst: 345.00,
      sgst: 345.00,
      igst: 0.00,
      totalAmount: 5000.00,
      pdfGeneratedAt: '2026-07-22T14:35:00Z',
      paymentDueDate: '2026-08-21T23:59:59Z',
      status: 'UNPAID',
    }
  ];

  public deliveryTasks: DeliveryTask[] = [
    {
      id: 'dt-501',
      deliveryNumber: 'DEL-2026-0081',
      orderId: 'ord-1001',
      orderNumber: 'MSO-B2B-2026-0811',
      deliveryBoyId: 'usr-005',
      deliveryBoyName: 'David Miller',
      customerName: 'Apollo Hospital System (Dock #2)',
      phone: '+1 (800) 555-0199',
      deliveryAddress: '742 Evergreen Medical Parkway, Bay 2 Receiving Dock, Chicago IL 60601',
      currentLat: 41.8781,
      currentLng: -87.6298,
      estimatedArrivalMinutes: 18,
      status: 'IN_TRANSIT',
      otpCode: '8492',
      notes: 'Cold-chain insulated tote required for insulin transfer.',
      updatedAt: '2026-07-23T05:30:00Z',
    }
  ];

  public coupons: Coupon[] = [
    {
      id: 'cpn-01',
      code: 'MEDSAVE10',
      discountPercent: 10,
      maxDiscount: 50,
      minOrderAmount: 100,
      validUntil: '2026-12-31',
      usageCount: 142,
      active: true,
    },
    {
      id: 'cpn-02',
      code: 'B2BHEALTH2026',
      discountPercent: 15,
      maxDiscount: 500,
      minOrderAmount: 1000,
      validUntil: '2026-10-31',
      usageCount: 29,
      active: true,
    }
  ];

  public salesmanLeads: SalesmanLead[] = [
    {
      id: 'lead-01',
      salesmanId: 'usr-004',
      pharmacyName: 'St. Jude Community Pharmacy',
      contactPerson: 'Dr. Michael Chang',
      phone: '+1 (800) 555-9011',
      city: 'Chicago',
      estimatedMonthlyValue: 12000,
      status: 'NEGOTIATING',
    },
    {
      id: 'lead-02',
      salesmanId: 'usr-004',
      pharmacyName: 'Northwestern Diagnostic Center',
      contactPerson: 'Dr. Rachel Adams',
      phone: '+1 (800) 555-9022',
      city: 'Chicago',
      estimatedMonthlyValue: 35000,
      status: 'ONBOARDED',
    }
  ];

  public auditLogs: AuditLog[] = [
    {
      id: 'aud-001',
      userId: 'usr-001',
      userName: 'Dr. Arthur Vance',
      userRole: 'SUPER_ADMIN',
      action: 'SYSTEM_BOOT',
      module: 'SECURITY',
      details: 'MedSupply Modular Monolith initialized with Spring Boot 3.5 DDD specs & PostgreSQL 16 schema.',
      ipAddress: '192.168.1.100',
      timestamp: '2026-07-23T05:00:00Z',
    },
    {
      id: 'aud-002',
      userId: 'usr-002',
      userName: 'Sarah Jenkins',
      userRole: 'ADMIN',
      action: 'BATCH_EXPIRY_AUDIT',
      module: 'INVENTORY',
      details: 'FEFO Check flagged Batch #AMX-2025-081 near expiry (Exp: 2026-08-15).',
      ipAddress: '192.168.1.102',
      timestamp: '2026-07-23T05:15:00Z',
    }
  ];

  public getMetrics(): SystemMetrics {
    const totalRevenueB2B = this.orders
      .filter(o => o.orderType === 'B2B' && o.paymentStatus !== 'REFUNDED')
      .reduce((sum, o) => sum + o.totalAmount, 0);

    const totalRevenueB2C = this.orders
      .filter(o => o.orderType === 'B2C' && o.paymentStatus !== 'REFUNDED')
      .reduce((sum, o) => sum + o.totalAmount, 0);

    const nearExpiryCount = this.batches.filter(b => b.status === 'NEAR_EXPIRY').length;
    const expiredCount = this.batches.filter(b => b.status === 'EXPIRED').length;

    return {
      totalRevenueB2B,
      totalRevenueB2C,
      totalOrdersCount: this.orders.length,
      pendingOrdersCount: this.orders.filter(o => o.orderStatus === 'PENDING_APPROVAL').length,
      totalBatchesCount: this.batches.length,
      nearExpiryCount,
      expiredCount,
      activeWarehousesCount: this.warehouses.filter(w => w.status === 'OPERATIONAL').length,
      activeDeliveriesCount: this.deliveryTasks.filter(d => d.status === 'IN_TRANSIT').length,
    };
  }

  public addAuditLog(userId: string, userName: string, userRole: any, action: string, module: string, details: string, ipAddress: string = '127.0.0.1') {
    this.auditLogs.unshift({
      id: `aud-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      userId,
      userName,
      userRole,
      action,
      module,
      details,
      ipAddress,
      timestamp: new Date().toISOString(),
    });
  }
}

export const store = new MedSupplyStore();
